/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations['me_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/company': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Company */
    get: operations['get_company_company_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Company */
    patch: operations['update_company_company_patch'];
    trace?: never;
  };
  '/company/rates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Rates */
    get: operations['get_rates_company_rates_get'];
    /** Put Rates */
    put: operations['put_rates_company_rates_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/company/logo-upload-url': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logo Upload Url */
    post: operations['logo_upload_url_company_logo_upload_url_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/clients': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Clients */
    get: operations['list_clients_clients_get'];
    put?: never;
    /** Create Client */
    post: operations['create_client_clients_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/clients/{client_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Client */
    get: operations['get_client_clients__client_id__get'];
    put?: never;
    post?: never;
    /** Delete Client */
    delete: operations['delete_client_clients__client_id__delete'];
    options?: never;
    head?: never;
    /** Update Client */
    patch: operations['update_client_clients__client_id__patch'];
    trace?: never;
  };
  '/jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Jobs */
    get: operations['list_jobs_jobs_get'];
    put?: never;
    /** Create Job */
    post: operations['create_job_jobs_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/jobs/{job_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Job */
    get: operations['get_job_jobs__job_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Job */
    patch: operations['update_job_jobs__job_id__patch'];
    trace?: never;
  };
  '/jobs/{job_id}/transition': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transition Job */
    post: operations['transition_job_jobs__job_id__transition_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/catalog/assemblies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Assemblies */
    get: operations['list_assemblies_catalog_assemblies_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/catalog/assemblies/{code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Assembly */
    get: operations['get_assembly_catalog_assemblies__code__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Assembly */
    patch: operations['update_assembly_catalog_assemblies__code__patch'];
    trace?: never;
  };
  '/catalog/modifiers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Modifiers */
    get: operations['list_modifiers_catalog_modifiers_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/catalog/materials': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Materials */
    get: operations['list_materials_catalog_materials_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pricing/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview */
    post: operations['preview_pricing_preview_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/jobs/{job_id}/captures': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Captures */
    get: operations['list_captures_jobs__job_id__captures_get'];
    put?: never;
    /** Create Capture */
    post: operations['create_capture_jobs__job_id__captures_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/captures/{capture_id}/complete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Complete Capture */
    post: operations['complete_capture_captures__capture_id__complete_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/jobs/{job_id}/estimates/generate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate */
    post: operations['generate_jobs__job_id__estimates_generate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/jobs/{job_id}/estimates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Estimates */
    get: operations['list_estimates_jobs__job_id__estimates_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/estimates/{estimate_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Estimate */
    get: operations['get_estimate_estimates__estimate_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AssemblyList */
    AssemblyList: {
      /** Items */
      items: components['schemas']['AssemblyOut'][];
    };
    /** AssemblyOut */
    AssemblyOut: {
      /** Code */
      code: string;
      /** Trade */
      trade: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Job Type Codes */
      job_type_codes: string[];
      /** Unit */
      unit: string;
      /** Labor Hours */
      labor_hours: string;
      /** Helper Hours */
      helper_hours: string;
      /** Labor Notes */
      labor_notes: string | null;
      /** Bom */
      bom: {
        [key: string]: unknown;
      }[];
      /** Modifiers Allowed */
      modifiers_allowed: string[];
      /** Option Tiers */
      option_tiers:
        | {
            [key: string]: unknown;
          }[]
        | null;
      /** Version */
      version: number;
      /** Status */
      status: string;
    };
    /** AssemblyPatch */
    AssemblyPatch: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Labor Hours */
      labor_hours?: number | string | null;
      /** Helper Hours */
      helper_hours?: number | string | null;
      /** Labor Notes */
      labor_notes?: string | null;
      /** Modifiers Allowed */
      modifiers_allowed?: string[] | null;
      /** Status */
      status?: string | null;
    };
    /** CaptureCreated */
    CaptureCreated: {
      capture: components['schemas']['CaptureOut'];
      /** Upload Url */
      upload_url: string;
      /** Upload Token */
      upload_token: string;
    };
    /** CaptureIn */
    CaptureIn: {
      /**
       * Kind
       * @enum {string}
       */
      kind: 'photo' | 'audio';
      /** Duration S */
      duration_s?: number | string | null;
      /** Exif */
      exif?: {
        [key: string]: unknown;
      } | null;
    };
    /** CaptureOut */
    CaptureOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Job Id
       * Format: uuid
       */
      job_id: string;
      /** Kind */
      kind: string;
      /** Storage Path */
      storage_path: string;
      /** Upload State */
      upload_state: string;
      /** Duration S */
      duration_s: string | null;
      /** Has Transcript */
      has_transcript: boolean;
      /** Has Vision Findings */
      has_vision_findings: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ClientIn */
    ClientIn: {
      /** Name */
      name: string;
      /** Phone */
      phone?: string | null;
      /** Email */
      email?: string | null;
      /** Address */
      address?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /** ClientOut */
    ClientOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Phone */
      phone: string | null;
      /** Email */
      email: string | null;
      /** Address */
      address: string | null;
      /** Notes */
      notes: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ClientPatch */
    ClientPatch: {
      /** Name */
      name?: string | null;
      /** Phone */
      phone?: string | null;
      /** Email */
      email?: string | null;
      /** Address */
      address?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /** CompanyOut */
    CompanyOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Trade */
      trade: string;
      /** Logo Url */
      logo_url: string | null;
      /** License Number */
      license_number: string | null;
      /** Insurance Line */
      insurance_line: string | null;
      /** Phone */
      phone: string | null;
      /** Email */
      email: string | null;
      /** Address */
      address: string | null;
      /** Timezone */
      timezone: string;
      /** Settings */
      settings: {
        [key: string]: unknown;
      };
    };
    /** CompanyPatch */
    CompanyPatch: {
      /** Name */
      name?: string | null;
      /** Logo Url */
      logo_url?: string | null;
      /** License Number */
      license_number?: string | null;
      /** Insurance Line */
      insurance_line?: string | null;
      /** Phone */
      phone?: string | null;
      /** Email */
      email?: string | null;
      /** Address */
      address?: string | null;
      /** Timezone */
      timezone?: string | null;
      /** Settings */
      settings?: {
        [key: string]: unknown;
      } | null;
    };
    /** EstimateDetail */
    EstimateDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Job Id
       * Format: uuid
       */
      job_id: string;
      /** Version */
      version: number;
      /** Status */
      status: string;
      /** Source */
      source: string;
      /** Totals */
      totals: {
        [key: string]: unknown;
      } | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Scope Prose */
      scope_prose: string | null;
      /** Ai Output */
      ai_output: {
        [key: string]: unknown;
      } | null;
      /** Lines */
      lines: components['schemas']['EstimateLineOut'][];
    };
    /** EstimateLineOut */
    EstimateLineOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Position */
      position: number;
      /** Assembly Code */
      assembly_code: string | null;
      /** Description */
      description: string;
      /** Qty */
      qty: string;
      /** Unit */
      unit: string | null;
      /** Material Cost */
      material_cost: string | null;
      /** Labor Hours */
      labor_hours: string | null;
      /** Labor Rate */
      labor_rate: string | null;
      /** Line Type */
      line_type: string;
      /** Price Source */
      price_source: string;
      /** Confidence */
      confidence: string;
      /** Editable Note */
      editable_note: string | null;
      /** Totals */
      totals: {
        [key: string]: unknown;
      } | null;
    };
    /** EstimateSummary */
    EstimateSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Job Id
       * Format: uuid
       */
      job_id: string;
      /** Version */
      version: number;
      /** Status */
      status: string;
      /** Source */
      source: string;
      /** Totals */
      totals: {
        [key: string]: unknown;
      } | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** GenerateQueued */
    GenerateQueued: {
      /**
       * Status
       * @default queued
       */
      status: string;
      /**
       * Job Id
       * Format: uuid
       */
      job_id: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /** JobIn */
    JobIn: {
      /** Title */
      title: string;
      /** Client Id */
      client_id?: string | null;
      /** Job Type Code */
      job_type_code?: string | null;
      /** Address */
      address?: string | null;
    };
    /** JobOut */
    JobOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string;
      /** Status */
      status: string;
      /** Job Type Code */
      job_type_code: string | null;
      /** Address */
      address: string | null;
      /** Client Id */
      client_id: string | null;
      /** Client Name */
      client_name: string | null;
      /** Allowed Transitions */
      allowed_transitions: string[];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** JobPatch */
    JobPatch: {
      /** Title */
      title?: string | null;
      /** Client Id */
      client_id?: string | null;
      /** Job Type Code */
      job_type_code?: string | null;
      /** Address */
      address?: string | null;
    };
    /**
     * LineBreakdown
     * @description The 'show the math' payload for the estimate editor.
     */
    LineBreakdown: {
      /** Base Labor Hours */
      base_labor_hours: string;
      /** Company Override Mult */
      company_override_mult: string;
      /** Modifier Applications */
      modifier_applications: components['schemas']['ModifierApplication'][];
      /** Unit Labor Hours */
      unit_labor_hours: string;
      /** Total Labor Hours */
      total_labor_hours: string;
      /** Total Helper Hours */
      total_helper_hours: string;
      /** Labor Rate */
      labor_rate: string;
      /** Helper Rate */
      helper_rate: string;
      /** Labor Cost */
      labor_cost: string;
      /** Helper Cost */
      helper_cost: string;
      /** Materials */
      materials: components['schemas']['MaterialBreakdownItem'][];
      /** Material Cost */
      material_cost: string;
      /** Cost Total */
      cost_total: string;
      /**
       * Pricing Model
       * @enum {string}
       */
      pricing_model: 'margin' | 'markup';
      /** Pct Applied */
      pct_applied: string;
    };
    /** LogoUploadOut */
    LogoUploadOut: {
      /** Upload Url */
      upload_url: string;
      /** Token */
      token: string;
      /** Storage Path */
      storage_path: string;
    };
    /** MarginCheck */
    MarginCheck: {
      /** Cost Total */
      cost_total: string;
      /** Price Basis */
      price_basis: string;
      /** Effective Margin Pct */
      effective_margin_pct: string;
      /** Target Margin Pct */
      target_margin_pct: string;
      /** Below Target */
      below_target: boolean;
      /** Below Floor */
      below_floor: boolean;
    };
    /** MaterialBreakdownItem */
    MaterialBreakdownItem: {
      /** Sku */
      sku: string;
      /** Description */
      description: string;
      /** Unit Price */
      unit_price: string;
      /** Qty */
      qty: string;
      /** Extended */
      extended: string;
    };
    /** MaterialList */
    MaterialList: {
      /** Items */
      items: components['schemas']['MaterialOut'][];
    };
    /** MaterialOut */
    MaterialOut: {
      /** Sku */
      sku: string;
      /** Description */
      description: string;
      /** Unit */
      unit: string;
      /** Category */
      category: string | null;
      /** Base Price */
      base_price: string;
      /** Source */
      source: string | null;
    };
    /** MeCompanyOut */
    MeCompanyOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Trade */
      trade: string;
      /** Timezone */
      timezone: string;
    };
    /** ModifierApplication */
    ModifierApplication: {
      /** Code */
      code: string;
      /** Name */
      name: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: 'multiply' | 'add';
      /** Hours Before */
      hours_before: string;
      /** Hours After */
      hours_after: string;
    };
    /** ModifierList */
    ModifierList: {
      /** Items */
      items: components['schemas']['ModifierOut'][];
    };
    /** ModifierOut */
    ModifierOut: {
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Effect */
      effect: {
        [key: string]: unknown;
      };
      /** Version */
      version: number;
    };
    /** PreviewAdjustments */
    PreviewAdjustments: {
      /**
       * Discount
       * @default 0
       */
      discount: number | string;
      /** Margin Override Pct */
      margin_override_pct?: number | string | null;
    };
    /** PreviewAllowance */
    PreviewAllowance: {
      /** Description */
      description: string;
      /** Amount */
      amount: number | string;
      /**
       * Reason
       * @default
       */
      reason: string;
    };
    /** PreviewIn */
    PreviewIn: {
      /** Assemblies */
      assemblies?: components['schemas']['PreviewLine'][];
      /** Allowances */
      allowances?: components['schemas']['PreviewAllowance'][];
      /**
       * @default {
       *       "discount": "0"
       *     }
       */
      adjustments: components['schemas']['PreviewAdjustments'];
    };
    /** PreviewLine */
    PreviewLine: {
      /** Code */
      code: string;
      /**
       * Qty
       * @default 1
       */
      qty: number | string;
      /** Modifiers */
      modifiers?: string[];
      /** Selected Tier */
      selected_tier?: ('good' | 'better' | 'best') | null;
    };
    /** PricedEstimate */
    PricedEstimate: {
      /** Engine Version */
      engine_version: string;
      /** Lines */
      lines: components['schemas']['PricedLine'][];
      /** Subtotal Material */
      subtotal_material: string;
      /** Subtotal Labor */
      subtotal_labor: string;
      /** Subtotal */
      subtotal: string;
      /** Tax */
      tax: string;
      /** Total */
      total: string;
      margin_check: components['schemas']['MarginCheck'];
    };
    /** PricedLine */
    PricedLine: {
      /** Position */
      position: number;
      /** Assembly Code */
      assembly_code: string | null;
      /** Description */
      description: string;
      /** Qty */
      qty: string;
      /** Unit */
      unit: string;
      /**
       * Line Type
       * @enum {string}
       */
      line_type:
        | 'standard'
        | 'allowance'
        | 'verify'
        | 'option_good'
        | 'option_better'
        | 'option_best'
        | 'discount';
      /**
       * Price Source
       * @default engine
       * @enum {string}
       */
      price_source: 'engine' | 'manual' | 'pricebook';
      /**
       * Confidence
       * @default known
       * @enum {string}
       */
      confidence: 'known' | 'allowance' | 'verify';
      /** Unit Price */
      unit_price: string;
      /** Total */
      total: string;
      /** Material Cost */
      material_cost: string;
      /** Labor Hours */
      labor_hours: string;
      /** Labor Rate */
      labor_rate: string;
      /**
       * Included
       * @default true
       */
      included: boolean;
      /**
       * Editable Note
       * @default
       */
      editable_note: string;
      breakdown?: components['schemas']['LineBreakdown'] | null;
    };
    /** RatesOut */
    RatesOut: {
      /** Labor Rate */
      labor_rate: string;
      /** Helper Rate */
      helper_rate: string | null;
      /** Target Margin Pct */
      target_margin_pct: string;
      /** Tax Rate Pct */
      tax_rate_pct: string;
      /** Markup Model */
      markup_model: string;
      /** Confirmed */
      confirmed: boolean;
    };
    /** RatesPut */
    RatesPut: {
      /** Labor Rate */
      labor_rate: number | string;
      /** Helper Rate */
      helper_rate?: number | string | null;
      /** Target Margin Pct */
      target_margin_pct: number | string;
      /** Tax Rate Pct */
      tax_rate_pct: number | string;
      /** Markup Model */
      markup_model: string;
      /**
       * Confirmed
       * @default true
       */
      confirmed: boolean;
    };
    /** TransitionIn */
    TransitionIn: {
      /** To Status */
      to_status: string;
    };
    /** UserOut */
    UserOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Role */
      role: string;
      /** Name */
      name: string | null;
      company: components['schemas']['MeCompanyOut'];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  me_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
    };
  };
  get_company_company_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CompanyOut'];
        };
      };
    };
  };
  update_company_company_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CompanyPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CompanyOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_rates_company_rates_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RatesOut'];
        };
      };
    };
  };
  put_rates_company_rates_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RatesPut'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RatesOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logo_upload_url_company_logo_upload_url_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LogoUploadOut'];
        };
      };
    };
  };
  list_clients_clients_get: {
    parameters: {
      query?: {
        search?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClientOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_client_clients_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ClientIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClientOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_client_clients__client_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        client_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClientOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_client_clients__client_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        client_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_client_clients__client_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        client_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ClientPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClientOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_jobs_jobs_get: {
    parameters: {
      query?: {
        status?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_job_jobs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JobIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_job_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_job_jobs__job_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JobPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  transition_job_jobs__job_id__transition_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_assemblies_catalog_assemblies_get: {
    parameters: {
      query?: {
        job_type?: string | null;
        q?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssemblyList'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_assembly_catalog_assemblies__code__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssemblyOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_assembly_catalog_assemblies__code__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AssemblyPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssemblyOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_modifiers_catalog_modifiers_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ModifierList'];
        };
      };
    };
  };
  list_materials_catalog_materials_get: {
    parameters: {
      query?: {
        q?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MaterialList'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  preview_pricing_preview_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PreviewIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PricedEstimate'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_captures_jobs__job_id__captures_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CaptureOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_capture_jobs__job_id__captures_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CaptureIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CaptureCreated'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  complete_capture_captures__capture_id__complete_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        capture_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CaptureOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  generate_jobs__job_id__estimates_generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GenerateQueued'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_estimates_jobs__job_id__estimates_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EstimateSummary'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_estimate_estimates__estimate_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        estimate_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EstimateDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
