"""Export the OpenAPI spec to apps/api/openapi.json.

Run: uv run python scripts/export_openapi.py
The typed TS client is then generated by `pnpm --filter @fieldquote/shared-types generate`.
"""

import json
from pathlib import Path

from fieldquote.main import create_app


def main() -> None:
    spec = create_app().openapi()
    out = Path(__file__).resolve().parent.parent / "openapi.json"
    out.write_text(json.dumps(spec, indent=2), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
